
GET http://localhost:5000/admin/get-users/5f2d7a270bd5a71a32ebda0b
###
GET http://localhost:5000/admin/games

###


DELETE http://localhost:5000/admin/5f327d8e6899820aa4e1d97e

###
GET http://localhost:5000/
###

PATCH http://localhost:5000/admin/5f327e5a6488470b0864cee9
Content-Type: application/json

{
    "title": "New title"
}
###

POST http://localhost:5000/admin/
Content-Type: application/json

{   
    
    "game_id":1234,
    "title":"Cock of Doody",
    "cdkey":"COD-efgh-ijkl-mnopq",
    "picture":"http://hello",
    "price":60
}

###
POST http://localhost:5000/payment/5f43ba3c6414493e77608943